name: vital-industry-p4e
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.23.1
  - pandas
  - matplotlib
  - seaborn
  - pytest=7.1.2
  - ipykernel
  - pip
  - pip:
    - tqdm==4.62.3
